version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379" 
  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=myPassword123456789
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=lee0ne203@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=myPassword123456789
    ports:
      - "5050:80" 
    volumes:
      - pgadmin_data:/root/.pgadmin 
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:MongoConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:RedisConnectionString=basketdb:6379"
    depends_on: 
      - basketdb
    ports:
      - "8001:80"

